version: '3.9'

services:
  backend:
    image: mongoose-poo-backend:latest
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URI=${MONGO_URI_CONTAINER}
    container_name: mongoose-poo-backend
    links:
      - mongo
    volumes:
    - ./:/app
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    container_name: 30.1-mongoose-poo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    cap_add:
    - SYS_NICE

networks:
  default:
    external: true
    name: mongoose-poo-network